version: '3.8'

services:
  jean-pierre-agenda:
    build:
      context: .
      dockerfile: Dockerfile
    # Coolify gestiona automáticamente la red externa y el dominio.
    # El puerto interno que expone la app se mapea automáticamente.
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Coolify inyectará las variables de entorno automáticamente si las defines en su panel (sección Environment Variables).
      # No es necesario dejarlas aquí "quemadas" o repetidas, al declararlas así, Docker tomará el valor del host (Coolify).
      - GEMINI_API_KEY
      - APP_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - ADMIN_EMAIL
    restart: unless-stopped

